### ISSUE TITLE
PHP fatal error when author has no image assigned

### ISSUE THREAD

**Issue by digitalbricks** [kongondo/Blog#35]
Hello kongondo,

first, thank you very much for the great module!

Working with ProcessBlog the first time, i encountered the following error:
If a user with the role "blog-author" has no image assigned ("blog_images" field empty) i get an fatal error when opening Blog --> Authors in the PW backend:

> Call to a member function size() on boolean
> File: .../modules/ProcessBlog/ProcessBlog.module:1686

This is because the check for an image in the line above, line 1685, returns true if no image is present.

https://github.com/kongondo/Blog/blob/eed59c095399fff49c6eb0913e0f2ad515331dd9/ProcessBlog.module#L1685

**Quick fix:**
I solved this by replacing `!empty()` with `count()`:
```php
$authorPhoto = count($author->blog_images) ?
```

**Comment by kongondo** [comment]
Hi @digitalbricks ,

Thanks for reminding me about this. The bug was [reported](https://processwire.com/talk/topic/17105-module-blog/?do=findComment&comment=199470) in the forums in March 2020. I didn't have time to work on a commit so I offered a temporary solution (similar to yours) [here](https://processwire.com/talk/topic/17105-module-blog/?do=findComment&comment=199472). Please have a look.

Thanks.

**Comment by kongondo** [comment]
Closing this as fixed in 2.4.6 (a13af30).
